# Generated by Django 2.2.6 on 2019-10-30 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_auto_20191030_1142'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groups',
            options={},
        ),
        migrations.AlterModelOptions(
            name='locations',
            options={},
        ),
        migrations.AlterModelOptions(
            name='teachers',
            options={},
        ),
    ]
