# Generated by Django 2.2.6 on 2019-10-30 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_auto_20191030_1149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groups',
            name='location_id',
        ),
        migrations.AddField(
            model_name='groups',
            name='location',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='bot.Locations'),
        ),
        migrations.AlterField(
            model_name='groups',
            name='teacher',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='bot.Teachers'),
        ),
    ]
