# Generated by Django 2.2.6 on 2019-10-30 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_auto_20191030_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='location',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.Locations'),
        ),
        migrations.AlterField(
            model_name='groups',
            name='teacher',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.Teachers'),
        ),
    ]
