# Generated by Django 2.2.6 on 2019-11-08 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_auto_20191108_2311'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='command',
            options={'verbose_name': 'комманду', 'verbose_name_plural': 'комманды'},
        ),
        migrations.AlterModelOptions(
            name='day',
            options={'ordering': ('id',), 'verbose_name': 'день недели', 'verbose_name_plural': 'дни недели'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'событие', 'verbose_name_plural': 'события'},
        ),
        migrations.AlterModelOptions(
            name='eventtype',
            options={'verbose_name': 'тип события', 'verbose_name_plural': 'типы событий'},
        ),
        migrations.AlterModelOptions(
            name='genericanswer',
            options={'verbose_name': 'обычный ответ', 'verbose_name_plural': 'обычные ответы'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'группу', 'verbose_name_plural': 'группы'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'локацию', 'verbose_name_plural': 'локации'},
        ),
        migrations.AlterModelOptions(
            name='signup',
            options={'verbose_name': 'запись', 'verbose_name_plural': 'записи'},
        ),
        migrations.AlterModelOptions(
            name='situationanswer',
            options={'verbose_name': 'ситуационный ответ', 'verbose_name_plural': 'ситуационные ответы'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': 'предмет', 'verbose_name_plural': 'предметы'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'учителя', 'verbose_name_plural': 'учителя'},
        ),
        migrations.AlterField(
            model_name='command',
            name='description',
            field=models.TextField(verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='command',
            name='name',
            field=models.CharField(max_length=50, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='command',
            name='no_argument_response',
            field=models.CharField(max_length=100, verbose_name='ответ когда нету аргумента'),
        ),
        migrations.AlterField(
            model_name='command',
            name='not_found_response',
            field=models.CharField(max_length=100, verbose_name='ответ когда не найдено'),
        ),
        migrations.AlterField(
            model_name='day',
            name='name',
            field=models.CharField(max_length=50, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_from',
            field=models.DateField(verbose_name='дата с'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_to',
            field=models.DateField(verbose_name='дата на'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='event',
            name='group',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.Group', verbose_name='группа'),
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.EventType', verbose_name='тип'),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='name',
            field=models.CharField(max_length=50, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='genericanswer',
            name='input',
            field=models.CharField(max_length=50, verbose_name='ввод'),
        ),
        migrations.AlterField(
            model_name='genericanswer',
            name='output',
            field=models.TextField(verbose_name='вывод'),
        ),
        migrations.AlterField(
            model_name='group',
            name='days',
            field=models.ManyToManyField(blank=True, null=True, to='bot.Day', verbose_name='дни'),
        ),
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.CharField(blank=True, max_length=255, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='group',
            name='location',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.Location', verbose_name='локация'),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=50, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='group',
            name='subject',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.Subject', verbose_name='предмет'),
        ),
        migrations.AlterField(
            model_name='group',
            name='teacher',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.Teacher', verbose_name='учитель'),
        ),
        migrations.AlterField(
            model_name='group',
            name='time_end',
            field=models.TimeField(verbose_name='время конца'),
        ),
        migrations.AlterField(
            model_name='group',
            name='time_start',
            field=models.TimeField(verbose_name='время начала'),
        ),
        migrations.AlterField(
            model_name='location',
            name='building',
            field=models.CharField(max_length=50, verbose_name='здание'),
        ),
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.CharField(max_length=50, verbose_name='город'),
        ),
        migrations.AlterField(
            model_name='location',
            name='country',
            field=models.CharField(max_length=50, verbose_name='страна'),
        ),
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.FloatField(verbose_name='широта'),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.FloatField(verbose_name='долгота'),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=50, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='location',
            name='region',
            field=models.CharField(max_length=50, verbose_name='регион'),
        ),
        migrations.AlterField(
            model_name='location',
            name='street',
            field=models.CharField(max_length=50, verbose_name='улица'),
        ),
        migrations.AlterField(
            model_name='signup',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='имя'),
        ),
        migrations.AlterField(
            model_name='signup',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='фамилия'),
        ),
        migrations.AlterField(
            model_name='signup',
            name='location',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.Location', verbose_name='локация'),
        ),
        migrations.AlterField(
            model_name='signup',
            name='middle_name',
            field=models.CharField(max_length=50, verbose_name='отчество'),
        ),
        migrations.AlterField(
            model_name='signup',
            name='notes',
            field=models.TextField(verbose_name='примечания'),
        ),
        migrations.AlterField(
            model_name='signup',
            name='subject',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.Subject', verbose_name='предмет'),
        ),
        migrations.AlterField(
            model_name='situationanswer',
            name='output',
            field=models.TextField(verbose_name='вывод'),
        ),
        migrations.AlterField(
            model_name='situationanswer',
            name='situation',
            field=models.CharField(max_length=50, verbose_name='ситуация'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='description',
            field=models.TextField(verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=50, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='age',
            field=models.IntegerField(verbose_name='возраст'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='имя'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='фамилия'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='mail',
            field=models.CharField(max_length=50, verbose_name='почта'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='middle_name',
            field=models.CharField(max_length=50, verbose_name='отчество'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='телефон'),
        ),
    ]
