# Generated by Django 2.2.6 on 2019-11-05 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_event_eventtype_signup'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='subject_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.Subject'),
        ),
    ]
