# Generated by Django 2.2.6 on 2019-11-05 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_group_subject_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='group_id',
            new_name='group',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='type_id',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='group',
            old_name='subject_id',
            new_name='subject',
        ),
        migrations.RenameField(
            model_name='signup',
            old_name='location_id',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='signup',
            old_name='subject_id',
            new_name='subject',
        ),
    ]
