# Generated by Django 2.2.6 on 2019-11-05 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0009_auto_20191105_2115'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='signup',
            old_name='lastname',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='signup',
            old_name='middlename',
            new_name='middle_name',
        ),
        migrations.RenameField(
            model_name='signup',
            old_name='description',
            new_name='notes',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='lastname',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='middlename',
            new_name='middle_name',
        ),
    ]
