# Generated by Django 2.2.6 on 2019-11-06 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0012_day'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='day',
            options={'ordering': ('id',)},
        ),
    ]
