# Generated by Django 2.2.6 on 2019-11-06 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0013_auto_20191106_1335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='days',
        ),
        migrations.AddField(
            model_name='group',
            name='days',
            field=models.ManyToManyField(blank=True, null=True, to='bot.Day'),
        ),
    ]
