# Generated by Django 2.2.6 on 2019-11-07 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0015_command_genericanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='no_argument_response',
            field=models.CharField(default='Test', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='command',
            name='not_found_response',
            field=models.CharField(default='Test', max_length=100),
            preserve_default=False,
        ),
    ]
