# Generated by Django 2.2.6 on 2019-11-08 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0016_auto_20191107_2211'),
    ]

    operations = [
        migrations.CreateModel(
            name='SituationAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situation', models.CharField(max_length=50)),
                ('output', models.TextField()),
            ],
        ),
    ]
